/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package employeeshiftvis;

import javax.swing.*;
import java.awt.*;

public class App extends JPanel {

    public static void main(String[] args) {
        JFrame mainFrame = new JFrame();
        mainFrame.setPreferredSize(new Dimension(1100, 800));
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        ShiftCreatePanel panel = new ShiftCreatePanel();

        mainFrame.add(panel);
        mainFrame.pack();
        mainFrame.setVisible(true);

    }
}
